### ISSUE TITLE
findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by dalbitresb12** [h-kanazawa/react-detectable-overflow#20]
Hi there!

I've noticed this warning in the console while using `react-detectable-overflow`:

> Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of ChildWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

This is actually a warning shown from the package `react-resize-detector` that this library uses. As stated in the [README](https://github.com/maslianok/react-resize-detector#refs), a `ref` is needed to not use the [deprecated](https://reactjs.org/link/strict-mode-find-node) `findDOMNode`.

I believe that a `ref` is needed in the `children` that is received and then passed using `targetRef` to the `ReactResizeDetector` component over here:

https://github.com/h-kanazawa/react-detectable-overflow/blob/e68f73978bdf7ca24b58468192fa2ee699fcd4bc/src/DetectableOverflow.tsx#L73-L78

Am I right? I'm fine with submitting a PR with this fix.

By the way, thank you for this great library!

**Comment by yuval9313** [comment]
Also joining this thread,
@dalbitresb12 I would love to see a PR on this matter
This lib is great and this error shouldn't be a factor whether to chose it or not .

**Comment by dalbitresb12** [comment]
I actually believe this one could be a breaking change, because the children should be a function so that it can return an element with the `ref` created. This would break existing React apps using this library because they would be passing an element instead of a function as the children. What do you think, @h-kanazawa?

**Comment by h-kanazawa** [comment]
Thanks for reporting. I'll check this issue soon.

**Comment by h-kanazawa** [comment]
I released 0.5.0 fixing the warnings.

@dalbitresb12 I tried to avoid breaking change. If this change breaks your apps or warnings are still logged, please let me know.

**Comment by dalbitresb12** [comment]
I'll try it out and check if anything breaks 😄

**Comment by dalbitresb12** [comment]
Hi @h-kanazawa.

I've updated `react-detectable-overflow` in my app, but I think the fix isn't working correctly. I'm still getting the error on the console.

![image](https://user-images.githubusercontent.com/7624090/97950780-086a8380-1d66-11eb-988b-b4162da3b992.png)

**Comment by h-kanazawa** [comment]
@dalbitresb12 Thanks for testing.
Can you attach your environment information for replication? e.g the versions of node, react, your browser, and a code snippet if possible.

**Comment by dalbitresb12** [comment]
@h-kanazawa Sure!

OS: Ubuntu 18.04 under WSL2 on Windows 10 2004
Node: v12.18.3
Yarn: v1.22.5
NPM: v6.14.6
React & React-DOM: v17.0.1
React Scripts: v4.0.0
Browser: Microsoft Edge 86.0.622.51 (Stable Channel)

I've setup a quick demo repository [here](https://github.com/dalbitresb12/react-detactable-overflow-error-demo). You can run it on your environment and test if the error still shows up or not.

![image](https://user-images.githubusercontent.com/7624090/98020204-b1e65f00-1dd0-11eb-8e8e-07e46224beae.png)

**Comment by dalbitresb12** [comment]
Hi @h-kanazawa! I previously added another comment with a test repo, but then I realized it was that I was missing a ref in another `ReactResizeDetector` that was a parent of the `DetectableOverflow` component I had. Thanks for fixing this error quickly! Now it is working correctly and without errors.

<details>
<summary>Code Snippet of my error</summary>

I was missing `targetRef` on the first `ReactResizeDetector` and didn't notice:

```jsx
<ReactResizeDetector targetRef={elemRef} handleWidth handleHeight={false} onResize={() => setOverflowed(false)}>
  <DetectableOverflow onChange={handleOverflow}>
    <span ref={elemRef}>{text}</span>
  </DetectableOverflow>
</ReactResizeDetector>
```
</details>

<details>
<summary>Previous comment that I deleted</summary>

Sure!

OS: Ubuntu 18.04 under WSL2 on Windows 10 2004
Node: v12.18.3
Yarn: v1.22.5
NPM: v6.14.6
React & React-DOM: v17.0.1
React Scripts: v4.0.0
Browser: Microsoft Edge 86.0.622.51 (Stable Channel)

I've setup a quick demo repository [here](https://github.com/dalbitresb12/react-detactable-overflow-error-demo). You can run it on your environment and test if the error still shows up or not.

![image](https://user-images.githubusercontent.com/7624090/98020204-b1e65f00-1dd0-11eb-8e8e-07e46224beae.png)

Note: I'll probably be deleting the repository in a few days.
</details>
